import type { App } from 'vue';
import PrimeVue from 'primevue/config';
import Aura from '@primevue/themes/aura';
import { ToastService } from 'primevue';

export function setupPrimeVue(app: App): void {
  app.use(PrimeVue, {
    theme: {
      preset: Aura,
      options: {
        darkModeSelector: '.dark',
      },
    },
    locale: ruLocaleForPrimeVue,
  });

  app.use(ToastService);
}

const ruLocaleForPrimeVue = {
  startsWith: 'Начинается с',
  contains: 'Содержит',
  notContains: 'Не содержит',
  endsWith: 'Заканчивается на',
  equals: 'Равно',
  notEquals: 'Не равно',
  noFilter: 'Без фильтра',
  lt: 'Меньше чем',
  lte: 'Меньше или равно',
  gt: 'Больше чем',
  gte: 'Больше или равно',
  dateIs: 'Дата равна',
  dateIsNot: 'Дата не равна',
  dateBefore: 'Дата раньше',
  dateAfter: 'Дата позже',
  clear: 'Очистить',
  apply: 'Применить',
  matchAll: 'Совпадение всех',
  matchAny: 'Совпадение любого',
  addRule: 'Добавить правило',
  removeRule: 'Удалить правило',
  accept: 'Да',
  reject: 'Нет',
  choose: 'Выбрать',
  upload: 'Загрузить',
  cancel: 'Отмена',
  completed: 'Завершено',
  pending: 'В ожидании',
  fileSizeTypes: ['Б', 'КБ', 'МБ', 'ГБ', 'ТБ', 'ПБ', 'ЭБ', 'ЗБ', 'ЙБ'],
  dayNames: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
  monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
  chooseYear: 'Выбрать год',
  chooseMonth: 'Выбрать месяц',
  chooseDate: 'Выбрать дату',
  prevDecade: 'Предыдущее десятилетие',
  nextDecade: 'Следующее десятилетие',
  prevYear: 'Предыдущий год',
  nextYear: 'Следующий год',
  prevMonth: 'Предыдущий месяц',
  nextMonth: 'Следующий месяц',
  prevHour: 'Предыдущий час',
  nextHour: 'Следующий час',
  prevMinute: 'Предыдущая минута',
  nextMinute: 'Следующая минута',
  prevSecond: 'Предыдущая секунда',
  nextSecond: 'Следующая секунда',
  am: 'до полудня',
  pm: 'после полудня',
  today: 'Сегодня',
  weekHeader: 'Нед',
  firstDayOfWeek: 1,
  showMonthAfterYear: false,
  dateFormat: 'dd.mm.yy',
  weak: 'Слабый',
  medium: 'Средний',
  strong: 'Сильный',
  passwordPrompt: 'Введите пароль',
  searchMessage: 'Доступно {0} результатов',
  selectionMessage: 'Выбрано {0} элементов',
  emptySelectionMessage: 'Ничего не выбрано',
  emptySearchMessage: 'Результаты не найдены',
  fileChosenMessage: '{0} файлов',
  noFileChosenMessage: 'Файл не выбран',
  emptyMessage: 'Нет доступных опций',
  aria: {
    trueLabel: 'Верно',
    falseLabel: 'Неверно',
    nullLabel: 'Не выбрано',
    star: '1 звезда',
    stars: '{star} звезд',
    selectAll: 'Все элементы выбраны',
    unselectAll: 'Все элементы сняты с выбора',
    close: 'Закрыть',
    previous: 'Предыдущий',
    next: 'Следующий',
    navigation: 'Навигация',
    scrollTop: 'Прокрутить вверх',
    moveTop: 'Переместить вверх',
    moveUp: 'Переместить выше',
    moveDown: 'Переместить ниже',
    moveBottom: 'Переместить вниз',
    moveToTarget: 'Переместить в цель',
    moveToSource: 'Переместить в источник',
    moveAllToTarget: 'Переместить все в цель',
    moveAllToSource: 'Переместить все в источник',
    pageLabel: 'Страница {page}',
    firstPageLabel: 'Первая страница',
    lastPageLabel: 'Последняя страница',
    nextPageLabel: 'Следующая страница',
    prevPageLabel: 'Предыдущая страница',
    rowsPerPageLabel: 'Строк на странице',
    jumpToPageDropdownLabel: 'Выпадающий список перехода на страницу',
    jumpToPageInputLabel: 'Поле ввода перехода на страницу',
    selectRow: 'Строка выбрана',
    unselectRow: 'Строка снята с выбора',
    expandRow: 'Строка развернута',
    collapseRow: 'Строка свернута',
    showFilterMenu: 'Показать меню фильтра',
    hideFilterMenu: 'Скрыть меню фильтра',
    filterOperator: 'Оператор фильтра',
    filterConstraint: 'Ограничение фильтра',
    editRow: 'Редактировать строку',
    saveEdit: 'Сохранить редактирование',
    cancelEdit: 'Отменить редактирование',
    listView: 'Вид списка',
    gridView: 'Вид сетки',
    slide: 'Слайд',
    slideNumber: '{slideNumber}',
    zoomImage: 'Увеличить изображение',
    zoomIn: 'Увеличить',
    zoomOut: 'Уменьшить',
    rotateRight: 'Повернуть вправо',
    rotateLeft: 'Повернуть влево'
  }
};
